print "HEllo world !!"
print "because its obvious ??"
print "its boring to type likw this"
print "but then how am gonna write 7 lines"
print "yes at leastt seven"
print "I kno i ma making lot of pspellign mistakse"
print "here i am at seevent line finaally!!!!!!!!!!!!!!!!!!!!!!!!"